name: test
on: [pull_request]

jobs:
  go-test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go test ./...

  helm-test:
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: 3.10.2
      HELM_UNITTEST_VERSION: 0.2.8
      KUBECONFORM_VERSION: 0.5.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: supplypike/setup-bin@v1
        with:
          uri: https://github.com/yannh/kubeconform/releases/download/v${{ env.KUBECONFORM_VERSION }}/kubeconform-linux-amd64.tar.gz
          name: kubeconform
          version: ${{ env.KUBECONFORM_VERSION }}

      - uses: supplypike/setup-bin@v1
        with:
          uri: https://get.helm.sh/helm-v${{ env.HELM_VERSION }}-linux-amd64.tar.gz
          name: helm
          version: ${{ env.HELM_VERSION }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - run: helm plugin install --version "${{ env.HELM_UNITTEST_VERSION }}" https://github.com/quintush/helm-unittest

      - run: ct --config ./hack/ct.yaml lint ./charts --all
